- 03_people.md
- _people/knut_reinert.md
- _people/manuel_holtgrewe.md
- _sass/minima/custom-styles.scss
Changes to peoples page:
-Categorie  (team, contributor, user, alumni) is now colllapsible.
-The team is not collapsed on page load
-People are collapsible and collapsed on load.
-Peoples avatar photos are round
-the bio and so on is positioned next to the avatar.
> [FEATURE] Make people and categories collapsible.

- 03_people.md
- _sass/minima/custom-styles.scss
- assets/css/style.scss
Before Desktop:
After Desktop: 
Before Mobile:
After Mobile:
> [FIX] people: enlargen image on mobile

- _layouts/app.html
Adding the possibility to add multiple citation for one application.
This is done like this:
**one citation:**
cite: fu_mi_publicationsXXXX
**Two citations:**
cite: [fu_mi_publicationsXXXX, fu_mi_publicationsXXXX]
> [FEAT] Adding multiple citations for one app.

- _layouts/app.html
- assets/css/style.scss
These images are now always fully contained and not cropped so that all information on these images is displayed.
> [FEAT] Adding new CSS for header images of apps. 

- 04_applications.md
- _apps/anise-and-basil.md
- _apps/fiona.md
- _apps/lara.md
- _apps/needle.md
Adds a Coming Soon section to the application page and adds the wip app needle
> Add wip category and application needle

- 04_applications.md
Fixes: https://github.com/seqan/www.seqan.de/issues/26 
And adds the SeqAn citation, because it is mentioned in the text.
> [FIX] Fix wording on Application page and add seqan citation.

- _people/manuel_holtgrewe.md
I think it only makes sense for the team to have positions
> [MISC] Remove position from alumni

- 03_people.md
I added the apps to the authors page.
It all looked a bit messy because there are three headings now so I highlighted the background in a light grey. I think this makes everything a bit more organized.
This also caused the boxes around the social icons to disappear (same color) and I found this to look quite nice. But of course  I can change that back to how it was. 💅  🌐
> [FEAT] Add belonging apps to people page.

- assets/css/style.scss
Adding 10px between all peoples.
adding grey background when unfolded.
removing blue border that appeared when clicked on a person.
> Add spacing and background to people.

- _posts/2019-06-06-seqan-3-0-0-release.md
When checking links in SeqAn3, I noticed that there is a missing redirect
> [FIX] missing redirect

- 04_applications.md
- _apps/bowtie.md
- _apps/delly.md
- _apps/flexbar.md
- _apps/mitotool.md
- _apps/mugsy.md
- _apps/popins.md
- _apps/tophat.md
I added short descriptions for all the apps like proposed in https://github.com/seqan/www.seqan.de/issues/57 
They are not yet styled but just integrated into the titles.
> Port Third Party Apps

- 04_applications.md
- _apps/anise-and-basil.md
- _apps/fiona.md
- _apps/gustaf.md
- _apps/igenvar.md
- _apps/jst.md
- _apps/lambda.md
- _apps/lara.md
- _apps/mason.md
- _apps/needle.md
- _apps/raptor.md
- _apps/razers3.md
- _apps/seqan_tcoffee.md
- _apps/slimm.md
- _apps/stellar.md
- _apps/string-similarity-search-and-join.md
- _apps/vaquita.md
- _apps/yara.md
- assets/css/style.scss
Resolves partly: https://github.com/seqan/www.seqan.de/issues/67 
I highlighted seqan3 badge by reducing the opacity of the seqan2 badge by 30%.
> [FEAT] Add a SeqAn Version Badge to every inhouse app.

- _people/birte_kehr.md
- _people/christopher_pockrandt.md
- _people/gianvito_urgese.md
- _people/kerstin_neubert.md
- _people/marcel_ehrhardt.md
- _people/simon_sasse.md
- _people/sven_boenigk.md
- _people/svenja_mehringer.md
- _people/wiep_vandertoorn.md
> [FIX] some typos

- _apps/raptor.md
- _data/publications.yml
Downloaded the current publications from:
http://publications.imp.fu-berlin.de/view/divisions/group=5Falgbioinf.html#group_2021
> Update publications 2021

- _apps/chopper.md
- _apps/mars.md
- _people/joerg_winkler.md
Add mars and chopper to WIP apps.
> Add Mars and Chopper

- _apps/dfi.md
- _apps/seqcons2.md
solves: https://github.com/seqan/www.seqan.de/issues/74
Port the two apps, that are not based on seqan1.
> Port old apps

- _posts/2019-06-06-seqan-3-0-0-release.md
Part of https://github.com/seqan/seqan3/issues/2821
> Snippet would not compile for gcc-7

- Gemfile
- _config.yml
- _posts/2020-01-23-seqan-3-0-1-release.md
- _posts/2021-05-28-seqan-3-0-3-release.md
- _posts/2021-11-11-seqan-3-1-0-release.md
> [MISC] use jemoji plugin

- _layouts/app.html
> [FIX] empty links

- _sass/minima/_base.scss
- _sass/minima/_layout.scss
- _sass/minima/initialize.scss
- assets/css/style.scss
See https://github.com/jekyll/minima/pull/700/commits/ad9dafa55e17bee7de322262165a40c38281ea6f
> [FIX] deprecation warnings
